export const products = [
  {
    ProductID: 1,
    ReferenceNumber: 11,
    Name: "P1",
    Price: 350,
    QuantityAvailable: 4,
    GiftOption: true,
    GiftPrice: 45,
  },
  {
    ProductID: 2,
    ReferenceNumber: 22,
    Name: "P2",
    Price: 100,
    QuantityAvailable: 1,
    GiftOption: true,
    GiftPrice: 45,
  },
  {
    ProductID: 3,
    ReferenceNumber: 33,
    Name: "P3",
    Price: 150,
    QuantityAvailable: 5,
    GiftOption: false,
    GiftPrice: 60,
  },
  {
    ProductID: 4,
    ReferenceNumber: 44,
    Name: "P4",
    Price: 70,
    QuantityAvailable: 2,
    GiftOption: false,
    GiftPrice: 48,
  },
  {
    ProductID: 5,
    ReferenceNumber: 11,
    Name: "P5",
    Price: 50,
    QuantityAvailable: 4,
    GiftOption: true,
    GiftPrice: 45,
  },
  {
    ProductID: 6,
    ReferenceNumber: 11,
    Name: "P5",
    Price: 50,
    QuantityAvailable: 4,
    GiftOption: true,
    GiftPrice: 45,
  },
  {
    ProductID: 7,
    ReferenceNumber: 11,
    Name: "P7",
    Price: 50,
    QuantityAvailable: 4,
    GiftOption: true,
    GiftPrice: 45,
  },
  {
    ProductID: 8,
    ReferenceNumber: 11,
    Name: "P8",
    Price: 50,
    QuantityAvailable: 4,
    GiftOption: false,
    GiftPrice: 45,
  },
];
